AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Serverless Airline Seat Reservation System

Resources:
  SeatReservationFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.handle_request
      Runtime: python3.9
      CodeUri: .
      MemorySize: 128
      Timeout: 30
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /seats
            Method: GET
        ReserveEvent:
          Type: Api
          Properties:
            Path: /reserve
            Method: POST
        CancelEvent:
          Type: Api
          Properties:
            Path: /cancel
            Method: POST
      Policies:
        - DynamoDBReadWritePolicy:
            TableName: !Ref SeatReservationTable

  SeatReservationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: seat-reservations-dev
      AttributeDefinitions:
        - AttributeName: seatId
          AttributeType: S
      KeySchema:
        - AttributeName: seatId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

